### ISSUE TITLE
Can no longer put 0 sized objects

### ISSUE THREAD

**Issue by sb10** [minio/minio-go#723]
In commit f8e360d4dc446022b46f1be1e8bdda5f736b9195 and previous, this worked, where source is the path to a 0 byte file (one that had just gotten truncated):

	_, err := a.client.FPutObject(a.bucket, dest, source, contentType)
	if err != nil {
		info, serr := os.Stat(source)
		if serr != nil {
			fmt.Printf("source was bad: %s\n", serr)
		} else {
			fmt.Printf("did FPutObject(%s, %s, %s, %s) (where source has size %d) and got %s\n", a.bucket, dest, source, contentType, info.Size(), err)
		}
	}

But since commit 8d69ba85cf79a5134321e7b10a7dbf3860511001 it fails with this error:

> did FPutObject(user, wr_tests/write.test, /tmp/[...]/wr_tests/write.test, text/plain; charset=utf-8) (where source has size 0) and got You must provide the Content-Length HTTP header.

Is this a bug, or should I now be doing something different?

**Comment by harshavardhana** [comment]
The problem is perhaps introduced in go1.8 from go1.7

**Comment by sb10** [comment]
Yes, I'm using go1.8.1 linux/amd64. But it is the commit I mentioned that breaks the behaviour.

**Comment by harshavardhana** [comment]
We have a fix submitted so should be merged..

**Comment by sb10** [comment]
Ah, I didn't check the pull requests. Yes, this seems like the same problem as discussed in #722

**Comment by harshavardhana** [comment]
Fixed by #722

**Comment by sb10** [comment]
This is not fixed for me. With commit 5d6d47070e65a765dbb32a9d1fc57c5ac8fba5ed, go 1.8 and using a Ceph Object Gateway I get:

    Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 400 Bad Request\r\nContent-Length: 122\r\nDate: Fri, 14 Jul 2017 11:32:31 GMT\r\nConnection: close\r\n\r\n"; err=<nil>
    did FPutObject(sb10, wr_tests/write.test, /tmp/[...]/wr_tests/write.test, text/plain; charset=utf-8) (where source has size 0) and got You must provide the Content-Length HTTP header.

**Comment by sb10** [comment]
Commit fe53a65ebc43b5d22626b29a19a3de81170e42d3 where this was initially fixed works fine, so it got broken again since then somehow...

**Comment by harshavardhana** [comment]
Can you provide a sample program and a full network trace ? With TraceOn

**Comment by sb10** [comment]
It works if in Client.newRequest() I comment out `signerType = c.overrideSignerType`, which wants to change my signerType from S3v4 to S3v4Streaming.

That is, the latest code goes down the S3v4Streaming code path and sets req.Body to some non-nil value.

I haven't looked through the code to see what sets overrideSignerType and why it's an incompatible value...

**Comment by harshavardhana** [comment]
It's not non no it uses streaming signature. Does Ceph not support streaming signature yet?

**Comment by harshavardhana** [comment]
Works fine with AWS S3 @sb10 

```sh
---------START-HTTP---------
PUT /myobject HTTP/1.1
Host: harshavardhana.s3-eu-central-1.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170714/eu-central-1/s3/aws4_request,SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
Content-Encoding: aws-chunked
Content-Type: application/octet-stream
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20170714T154223Z
X-Amz-Decoded-Content-Length: 0
Accept-Encoding: gzip

Content-Length: 0
Date: Fri, 14 Jul 2017 15:42:26 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Server: AmazonS3
X-Amz-Id-2: 8Rk48VyU5ZGt8zwx6O6qoGUmPlb5Z4xzNQndJNo1zlP6yaVaHZ63CWWfp3n1dJN7fFJLaKlbapQ=
X-Amz-Request-Id: 54A58BD2CCD9902A
---------END-HTTP---------
2017/07/14 08:42:24 Uploaded my-objectname  of size:  0 Successfully.
```

**Comment by harshavardhana** [comment]
> X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD

Check if this Ceph supports this streaming signature if yes then it should work fine like AWS S3 does. If it doesn't implement then you can either use 2.1.0 version or initialize your minio client with minio.NewV2()

**Comment by sb10** [comment]
../main.go:

    package main

    import (
        "fmt"
        "github.com/minio/minio-go"
        "os"
    )

    func main() {
        client, err := minio.New("cog.sanger.ac.uk", os.Getenv("AWS_ACCESS_KEY_ID"), os.Getenv("AWS_SECRET_ACCESS_KEY"), true)
        client.TraceOn(nil)
        
        bucket := "sb10"
        source := "foo"
        dest := "test.upload"
        contentType := "application/csv"
        
        f, err := os.OpenFile(source, os.O_RDONLY|os.O_CREATE, 0666)
        if err != nil {
            fmt.Printf("failed to create input file: %s\n", err)
            os.Exit(1)
        }
        f.Close()
        defer os.Remove(source)
        
        _, err = client.FPutObject(bucket, dest, source, contentType)
        info, serr := os.Stat(source)
        if err != nil {
            if serr != nil {
                fmt.Printf("source was bad: %s\n", serr)
            } else {
                fmt.Printf("did FPutObject(%s, %s, %s, %s) (where source has size %d) and got %s\n", bucket, dest, source, contentType, info.Size(), err)
            }
        } else {
            fmt.Printf("did FPutObject(%s, %s, %s, %s) (where source has size %d) and it worked\n", bucket, dest, source, contentType, info.Size())
        }
    }

Running with latest minio-go:

    $ git log -n 1 --pretty=format:"%H"
    5d6d47070e65a765dbb32a9d1fc57c5ac8fba5ed
    $ go run ../main.go
        ---------START-HTTP---------
    GET /sb10/?location= HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170714/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
    X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
    X-Amz-Date: 20170714T154153Z
    Accept-Encoding: gzip

    HTTP/1.1 200 OK
    Content-Length: 127
    Date: Fri, 14 Jul 2017 15:41:54 GMT
    X-Amz-Request-Id: tx0000000000000000bd8df-005968e642-48581d3-default
    ---------END-HTTP---------
    ---------START-HTTP---------
    PUT /sb10/test.upload HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Content-Length: 0
    Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170714/us-east-1/s3/aws4_request,SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
    Content-Encoding: aws-chunked
    Content-Type: application/csv
    X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
    X-Amz-Date: 20170714T154154Z
    X-Amz-Decoded-Content-Length: 0
    Accept-Encoding: gzip

    2017/07/14 15:41:54 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 400 Bad Request\r\nContent-Length: 122\r\nDate: Fri, 14 Jul 2017 15:41:54 GMT\r\nConnection: close\r\n\r\n"; err=<nil>
    HTTP/1.1 411 Length Required
    Content-Length: 228
    Accept-Ranges: bytes
    Content-Type: application/xml
    Date: Fri, 14 Jul 2017 15:41:54 GMT
    X-Amz-Request-Id: tx0000000000000000bd8e0-005968e642-48581d3-default

    <?xml version="1.0" encoding="UTF-8"?><Error><Code>MissingContentLength</Code><BucketName>sb10</BucketName><RequestId>tx0000000000000000bd8e0-005968e642-48581d3-default</RequestId><HostId>48581d3-default-default</HostId></Error>---------END-HTTP---------
    did FPutObject(sb10, test.upload, foo, application/csv) (where source has size 0) and got You must provide the Content-Length HTTP header.

Running again with my change:

    $ git diff
    diff --git a/api.go b/api.go
    index 6fe508a..2ace93a 100644
    --- a/api.go
    +++ b/api.go
    @@ -637,7 +637,7 @@ func (c Client) newRequest(method string, metadata requestMetadata) (req *http.R

            // Custom signer set then override the behavior.
            if c.overrideSignerType != credentials.SignatureDefault {
    -               signerType = c.overrideSignerType
    +               //signerType = c.overrideSignerType
            }

            // If signerType returned by credentials helper is anonymous,

Gives output:

    $ go run ../main.go
    ---------START-HTTP---------
    GET /sb10/?location= HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170714/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
    X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
    X-Amz-Date: 20170714T154656Z
    Accept-Encoding: gzip

    HTTP/1.1 200 OK
    Content-Length: 127
    Date: Fri, 14 Jul 2017 15:46:56 GMT
    X-Amz-Request-Id: tx00000000000000002d95d-005968e770-48c0c2a-default
    ---------END-HTTP---------
    ---------START-HTTP---------
    PUT /sb10/test.upload HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Content-Length: 0
    Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170714/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
    Content-Type: application/csv
    X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
    X-Amz-Date: 20170714T154656Z
    Accept-Encoding: gzip

    Accept-Ranges: bytes
    Content-Length: 0
    Date: Fri, 14 Jul 2017 15:46:56 GMT
    Etag: "d41d8cd98f00b204e9800998ecf8427e"
    X-Amz-Request-Id: tx00000000000000002d95e-005968e770-48c0c2a-default
    ---------END-HTTP---------
    did FPutObject(sb10, test.upload, foo, application/csv) (where source has size 0) and it worked

**Comment by sb10** [comment]
My understanding of http://javiermunhoz.com/blog/2016/08/31/aws4-chunked-upload-goes-upstream-in-ceph-rgw-s3.html is that v4 streaming is in COG as of 10.2.2, and I'm running 10.2.3. So it should work?

**Comment by harshavardhana** [comment]
The above is not correct @sb10 looks like Ceph doesn't support streaming signature if it does it is implemented wrong. It is incorrectly assuming content-length is not set.

> Content-Length: 0
Content length is set properly.

> <?xml version="1.0" encoding="UTF-8"?><Error><Code>MissingContentLength</Code><BucketName>sb10</BucketName><RequestId>tx0000000000000000bd8e0-005968e642-48581d3-default</RequestId><HostId>48581d3-default-default</HostId></Error>---------END-HTTP---------
Server incorrectly assumes otherwise.

Can you try with aws-sdk-java? with the same file and let us know with a debug trace. Let us know if aws-sdk-java works fine with the same file.

**Comment by harshavardhana** [comment]
NOTE: aws-sdk-java uses streaming signature by default.

**Comment by sb10** [comment]
Is there a quick and easy way for me to test with aws-sdk-java?

**Comment by harshavardhana** [comment]
> Is there a quick and easy way for me to test with aws-sdk-java?

You can also use fog ruby library if its a hassle which also supports streaming signature.  But would love to know if official AWS sdk works fine.

**Comment by sb10** [comment]
Using NewV2(), btw, also doesn't work:

    ---------START-HTTP---------
    GET /sb10/?location= HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Authorization: AWS **REDACTED**:**REDACTED**
    Date: Fri, 14 Jul 2017 15:58:03 GMT
    Accept-Encoding: gzip

    HTTP/1.1 200 OK
    Content-Length: 127
    Date: Fri, 14 Jul 2017 15:58:03 GMT
    X-Amz-Request-Id: tx00000000000000004bdf5-005968ea0b-4882612-default
    ---------END-HTTP---------
    ---------START-HTTP---------
    POST /sb10/test.upload?uploads= HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Content-Length: 0
    Authorization: AWS **REDACTED**:**REDACTED**
    Content-Type: application/csv
    Date: Fri, 14 Jul 2017 15:58:03 GMT
    Accept-Encoding: gzip

    HTTP/1.1 200 OK
    Content-Length: 246
    Content-Type: application/xml
    Date: Fri, 14 Jul 2017 15:58:03 GMT
    X-Amz-Request-Id: tx00000000000000004bdf6-005968ea0b-4882612-default
    ---------END-HTTP---------
    ---------START-HTTP---------
    POST /sb10/test.upload?uploadId=2~R1rf6oFMr2OxalxG_qDZNYzC8u2vt2M HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Content-Length: 99
    Authorization: AWS **REDACTED**:**REDACTED**
    Date: Fri, 14 Jul 2017 15:58:03 GMT
    Accept-Encoding: gzip

    HTTP/1.1 400 Bad Request
    Content-Length: 220
    Accept-Ranges: bytes
    Content-Type: application/xml
    Date: Fri, 14 Jul 2017 15:58:03 GMT
    X-Amz-Request-Id: tx00000000000000004bdf7-005968ea0b-4882612-default

    <?xml version="1.0" encoding="UTF-8"?><Error><Code>MalformedXML</Code><BucketName>sb10</BucketName><RequestId>tx00000000000000004bdf7-005968ea0b-4882612-default</RequestId><HostId>4882612-default-default</HostId></Error>---------END-HTTP---------
    ---------START-HTTP---------
    DELETE /sb10/test.upload?uploadId=2~R1rf6oFMr2OxalxG_qDZNYzC8u2vt2M HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Authorization: AWS **REDACTED**:**REDACTED**
    Date: Fri, 14 Jul 2017 15:58:03 GMT
    Accept-Encoding: gzip

    Date: Fri, 14 Jul 2017 15:58:03 GMT
    X-Amz-Request-Id: tx00000000000000004bdf8-005968ea0b-4882612-default
    ---------END-HTTP---------
    did FPutObject(sb10, test.upload, foo, application/csv) (where source has size 0) and got The XML you provided was not well-formed or did not validate against our published schema.

**Comment by harshavardhana** [comment]
This might be a separate problem @sb10

**Comment by harshavardhana** [comment]
> <?xml version="1.0" encoding="UTF-8"?><Error><Code>MalformedXML</Code><BucketName>sb10</BucketName><RequestId>tx00000000000000004bdf7-005968ea0b-4882612-default</RequestId><HostId>4882612-default-default</HostId></Error>---------END-HTTP---------

I can reproduce this problem seems like affects 0 byte objects..

**Comment by harshavardhana** [comment]
This should fix the problem for V2. 

```diff
$ git diff
diff --git a/api-put-object.go b/api-put-object.go
index c2a4203..1fa0a92 100644
--- a/api-put-object.go
+++ b/api-put-object.go
@@ -194,7 +194,7 @@ func (c Client) putObjectCommon(bucketName, objectName string, reader io.Reader,
        }
 
        if c.overrideSignerType.IsV2() {
-               if size > 0 && size < minPartSize {
+               if size >= 0 && size < minPartSize {
                        return c.putObjectNoChecksum(bucketName, objectName, reader, size, metadata, progress)
                }
                return c.putObjectMultipart(bucketName, objectName, reader, size, metadata, progress)
```

**Comment by sb10** [comment]
I confirm that fixes V2. Am I missing out on anything (esp. speed) by using V2 instead of V4, when COG supports everything else in V4 mode?

**Comment by harshavardhana** [comment]
> I confirm that fixes V2. Am I missing out on anything (esp. speed) by using V2 instead of V4, when COG supports everything else in V4 mode?
 
You won't be @sb10  V2 is just a legacy signature. You should open a bug with Ceph regarding the streaming signature part. I would love to validate aws-sdk-java with Ceph but do not have any Ceph instances running on my end.

**Comment by sb10** [comment]
I'll see if I can figure out using the java sdk next week.

**Comment by harshavardhana** [comment]
> I'll see if I can figure out using the java sdk next week.

Thanks let us know if you have more questions.

**Comment by sb10** [comment]
It works just fine with aws-java-sdk.

Install java:

    sudo add-apt-repository ppa:webupd8team/java
    sudo apt-get update
    sudo apt-get install oracle-java8-installer -y
    sudo apt-get install oracle-java8-set-default

Get a sample app:

    git clone https://github.com/awslabs/aws-java-sample.git
    cd aws-java-sample

Change pom.xml to:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>

        <groupId>com.amazonaws.samples</groupId>
        <artifactId>aws-java-sample</artifactId>
        <version>1.0</version>
        <packaging>jar</packaging>

        <name>aws-java-sample</name>
        <url>http://aws.amazon.com/sdkforjava</url>

        <properties>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
            <maven.compiler.target>1.8</maven.compiler.target>
        </properties>

        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk</artifactId>
                <version>1.11.106</version>
            </dependency>
        <dependency>
                <groupId>log4j</groupId>
                <artifactId>log4j</artifactId>
                <version>1.2.17</version>
            </dependency>
        </dependencies>

        <build>
            <resources>
                <resource>
                    <directory>${env.HOME}/.aws/</directory>
                </resource>
            </resources>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>1.2.1</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>java</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <mainClass>com.amazonaws.samples.S3Sample</mainClass>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </project>

Create log4j.properties:

    log4j.rootLogger=WARN, A1
    log4j.appender.A1=org.apache.log4j.ConsoleAppender
    log4j.appender.A1.layout=org.apache.log4j.PatternLayout
    log4j.appender.A1.layout.ConversionPattern=%d [%t] %-5p %c -  %m%n
    log4j.logger.org.apache.http.wire=DEBUG

Change src/main/java/com/amazonaws/samples/S3Sample.java to be:

    package com.amazonaws.samples;

    import java.io.BufferedReader;
    import java.io.File;
    import java.io.IOException;
    import java.io.InputStream;
    import java.io.InputStreamReader;
    import java.io.Writer;

    import com.amazonaws.AmazonClientException;
    import com.amazonaws.AmazonServiceException;
    import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;
    import com.amazonaws.services.s3.AmazonS3;
    import com.amazonaws.services.s3.AmazonS3ClientBuilder;
    import com.amazonaws.services.s3.model.GetObjectRequest;
    import com.amazonaws.services.s3.model.ListObjectsRequest;
    import com.amazonaws.services.s3.model.ObjectListing;
    import com.amazonaws.services.s3.model.PutObjectRequest;
    import com.amazonaws.services.s3.model.S3Object;
    import com.amazonaws.services.s3.model.S3ObjectSummary;

    public class S3Sample {
        public static void main(String[] args) throws IOException {
            AmazonS3 s3 = AmazonS3ClientBuilder.standard().withEndpointConfiguration(new EndpointConfiguration("https://cog.sanger.ac.uk", "us-east-1")).build();

            String bucketName = "sb10";
            String key = "test.upload";

            try {
                System.out.println("Uploading a new object to S3 from a file\n");
                s3.putObject(new PutObjectRequest(bucketName, key, createSampleFile()));

                System.out.println("Downloading an object");
                S3Object object = s3.getObject(new GetObjectRequest(bucketName, key));
                System.out.println("Content-Type: "  + object.getObjectMetadata().getContentType());
                displayTextInputStream(object.getObjectContent());

                System.out.println("Listing objects");
                ObjectListing objectListing = s3.listObjects(new ListObjectsRequest()
                        .withBucketName(bucketName)
                        .withPrefix("test"));
                for (S3ObjectSummary objectSummary : objectListing.getObjectSummaries()) {
                    System.out.println(" - " + objectSummary.getKey() + "  " +
                            "(size = " + objectSummary.getSize() + ")");
                }
                System.out.println();

                System.out.println("Deleting an object\n");
                s3.deleteObject(bucketName, key);
            } catch (AmazonServiceException ase) {
                System.out.println("Caught an AmazonServiceException, which means your request made it "
                        + "to Amazon S3, but was rejected with an error response for some reason.");
                System.out.println("Error Message:    " + ase.getMessage());
                System.out.println("HTTP Status Code: " + ase.getStatusCode());
                System.out.println("AWS Error Code:   " + ase.getErrorCode());
                System.out.println("Error Type:       " + ase.getErrorType());
                System.out.println("Request ID:       " + ase.getRequestId());
            } catch (AmazonClientException ace) {
                System.out.println("Caught an AmazonClientException, which means the client encountered "
                        + "a serious internal problem while trying to communicate with S3, "
                        + "such as not being able to access the network.");
                System.out.println("Error Message: " + ace.getMessage());
            }
        }

        private static File createSampleFile() throws IOException {
            File file = File.createTempFile("aws-java-sdk-", ".txt");
            file.deleteOnExit();
            return file;
        }

        private static void displayTextInputStream(InputStream input) throws IOException {
            BufferedReader reader = new BufferedReader(new InputStreamReader(input));
            while (true) {
                String line = reader.readLine();
                if (line == null) break;

                System.out.println("    " + line);
            }
            System.out.println();
        }
    }

Make sure ~/.aws/credentials and ~/.aws/config are as appropriate, then execute:

    mvn clean compile exec:java -Dlog4j.configuration=file:log4j.properties

The relevant part of the output is:

    Uploading a new object to S3 from a file

    2017-07-18 11:54:47,036 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "PUT /test.upload HTTP/1.1[\r][\n]"
    2017-07-18 11:54:47,036 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Host: sb10.cog.sanger.ac.uk[\r][\n]"
    2017-07-18 11:54:47,036 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
    2017-07-18 11:54:47,036 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170718/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "X-Amz-Date: 20170718T115446Z[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "User-Agent: aws-sdk-java/1.11.106 Linux/4.4.0-47-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.131-b11/1.8.0_131[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "amz-sdk-invocation-id: a0a2e46e-8eef-7b81-2b5a-18f1f4e46144[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Content-Type: text/plain[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Content-Length: 0[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
    2017-07-18 11:54:47,037 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 >> "[\r][\n]"
    2017-07-18 11:54:47,047 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
    2017-07-18 11:54:47,047 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "ETag: "d41d8cd98f00b204e9800998ecf8427e"[\r][\n]"
    2017-07-18 11:54:47,047 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "Content-Length: 0[\r][\n]"
    2017-07-18 11:54:47,047 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "Accept-Ranges: bytes[\r][\n]"
    2017-07-18 11:54:47,047 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "x-amz-request-id: tx000000000000000077fe7-00596df707-48c0c2a-default[\r][\n]"
    2017-07-18 11:54:47,048 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "Date: Tue, 18 Jul 2017 11:54:47 GMT[\r][\n]"
    2017-07-18 11:54:47,048 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "Connection: Keep-Alive[\r][\n]"
    2017-07-18 11:54:47,048 [com.amazonaws.samples.S3Sample.main()] DEBUG org.apache.http.wire -  http-outgoing-0 << "[\r][\n]"
    Downloading an object
    [...]
    Content-Type: text/plain

    Listing objects
    [...]
     - test.upload  (size = 0)

    Deleting an object
    [...]

I don't know if this is actually using the v4 streaming API or not, but I didn't have to do anything special. I'd request the same should apply to minio-go, just as it was a few commits ago.

**Comment by sb10** [comment]
Using NewV2 isn't really ideal for me, by the way, because this isn't just for my use with ceph, it's for anyone's use with any S3-like object store that minio-go supports.

Is it safe and acceptable to blindly use NewV2 with everything? Or do I have to figure out if I should use NewV2 or New()? How?

**Comment by sb10** [comment]
Actually, I also need the possibility of using NewWithRegion().

I'd much prefer to use New() or NewWithRegion() and have something like this implemented, which works for me:

    $ git diff
    diff --git a/api-put-object.go b/api-put-object.go
    index 1fa0a92..6d450a9 100644
    --- a/api-put-object.go
    +++ b/api-put-object.go
    @@ -209,7 +209,9 @@ func (c Client) putObjectCommon(bucketName, objectName string, reader io.Reader,
            }

            // Set streaming signature.
    -       c.overrideSignerType = credentials.SignatureV4Streaming
    +       if s3utils.IsAmazonEndpoint(c.endpointURL) {
    +               c.overrideSignerType = credentials.SignatureV4Streaming
    +       }

            if size < minPartSize {
                    return c.putObjectNoChecksum(bucketName, objectName, reader, size, metadata, progress)

**Comment by sb10** [comment]
For the record, I filed a bug against ceph: http://tracker.ceph.com/issues/20665

**Comment by harshavardhana** [comment]
The Java example is not using streaming APi. You can look at X-Amz-Content-Sha256 it should be mentioned as STREAMING. In the log it only says UNSIGNED-PAYLOAD 

Thanks for opening the bug with Ceph. NewV2() should work for all the scenarios unless you want to force region.

NewWithCredentials is lower level API which you can use as well providing your own credentials provider. 

Also don't change the override signature part it is important that we fix the server here until then please use V2

**Comment by sb10** [comment]
Your latest commit 75c1ccd3b1bb6a1c1a25864c1f8775bfabe161ec lets me use New() again with without error:

    [...]
    PUT /sb10/test.upload HTTP/1.1
    Host: cog.sanger.ac.uk
    User-Agent: Minio (linux; amd64) minio-go/3.0.0
    Content-Length: 0
    Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170719/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
    Content-Type: application/csv
    X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
    X-Amz-Date: 20170719T084756Z
    Accept-Encoding: gzip

    Accept-Ranges: bytes
    Content-Length: 0
    Date: Wed, 19 Jul 2017 08:47:56 GMT
    Etag: "d41d8cd98f00b204e9800998ecf8427e"
    X-Amz-Request-Id: tx0000000000000000794cb-00596f1cbc-48c0c2a-default
    ---------END-HTTP---------
    did FPutObject(sb10, test.upload, foo, application/csv) (where source has size 0) and it worked

Your comments for the commit don't suggest it, but did you intend this change to help my situation, and can this be relied on as the way you intentionally want minio-go to behave in the future?

**Comment by harshavardhana** [comment]
Yes @sb10 that is correct. But the problem still exists and you should follow up with Ceph to get it fixed. Your connection is SSL based the PR makes sure that for SSL we don't need to use streaming since there is no reason to do double checksum one on the wire with TLS and another sha256 sort of an optimization.

If you say used insecure communication then steaming signature is calculated for payload and you might see the problem again.
